config/routes.rb
BikeMissing::Application.routes.draw do
  resources :theft_reports

  root 'theft_reports#index'  

  

end

app/models/theft_report.rb
class TheftReport < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/theft_reports_controller.rb
class TheftReportsController < ApplicationController
  before_action :set_theft_report, only: [:show, :edit, :update, :destroy]

  # GET /theft_reports
  # GET /theft_reports.json
  def index
    @theft_reports = TheftReport.all
  end

  # GET /theft_reports/1
  # GET /theft_reports/1.json
  def show
  end

  # GET /theft_reports/new
  def new
    @theft_report = TheftReport.new
  end

  # GET /theft_reports/1/edit
  def edit
  end

  # POST /theft_reports
  # POST /theft_reports.json
  def create
    @theft_report = TheftReport.new(theft_report_params)

    respond_to do |format|
      if @theft_report.save
        format.html { redirect_to @theft_report, notice: 'Theft report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @theft_report }
      else
        format.html { render action: 'new' }
        format.json { render json: @theft_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theft_reports/1
  # PATCH/PUT /theft_reports/1.json
  def update
    respond_to do |format|
      if @theft_report.update(theft_report_params)
        format.html { redirect_to @theft_report, notice: 'Theft report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @theft_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theft_reports/1
  # DELETE /theft_reports/1.json
  def destroy
    @theft_report.destroy
    respond_to do |format|
      format.html { redirect_to theft_reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theft_report
      @theft_report = TheftReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theft_report_params
      params.require(:theft_report).permit(:location, :theft_date, :theft_way, :bike_data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/theft_reports_helper.rb
module TheftReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BikeMissing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/theft_reports/_form.html.erb
<%= form_for(@theft_report) do |f| %>
  <% if @theft_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theft_report.errors.count, "error") %> prohibited this theft_report from being saved:</h2>

      <ul>
      <% @theft_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :theft_date %><br>
    <%= f.datetime_select :theft_date %>
  </div>
  <div class="field">
    <%= f.label :theft_way,"How it happened?"%><br>
    <%= select_tag 'theft_report[theft_way]', options_for_select(["partial", "entire"]) %>
  </div>
  <div class="field">
    <%= f.label :bike_data,"Bike description"%><br>
    <%= f.text_area :bike_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theft_reports/edit.html.erb
<h1>Editing theft_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @theft_report %> |
<%= link_to 'Back', theft_reports_path %>

app/views/theft_reports/index.html.erb
<h1>Listing theft_reports</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Theft date</th>
      <th>Theft description</th>
      <th>Bike description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @theft_reports.each do |theft_report| %>
      <tr>
        <td><%= theft_report.location %></td>
        <td><%= theft_report.theft_date %></td>
        <td><%= theft_report.theft_way %></td>
        <td><%= theft_report.bike_data %></td>
        <td><%= link_to 'Show', theft_report %></td>
        <td><%= link_to 'Edit', edit_theft_report_path(theft_report) %></td>
        <td><%= link_to 'Destroy', theft_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theft report', new_theft_report_path %>

app/views/theft_reports/new.html.erb
<h1>New theft_report</h1>

<%= render 'form' %>

<%= link_to 'Back', theft_reports_path %>

app/views/theft_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @theft_report.location %>
</p>

<p>
  <strong>Theft date:</strong>
  <%= @theft_report.theft_date %>
</p>

<p>
  <strong>Theft way:</strong>
  <%= @theft_report.theft_way %>
</p>

<p>
  <strong>Bike data:</strong>
  <%= @theft_report.bike_data %>
</p>

<%= link_to 'Edit', edit_theft_report_path(@theft_report) %> |
<%= link_to 'Back', theft_reports_path %>